from Tests.Constants import SearchText as st

"""Login"""
EMAIL_USERNAME = 'olga@bamboo-card.com'
EMAIL_PASSWORD = 'Odol2706####'
NEW_PASSWORD = 'Odol2706'

""" Menu tests """

CASE_1 = [(st.ORDERS_TEXT[0], st.ORDER_HISTORY_TEXT, st.ORDER_HISTORY_URL),
          (st.ORDERS_TEXT[0], st.SOPPING_CARTS_TEXT, st.SOPPING_CARTS_URL)
          ]
z = [(st.ORDERS_TEXT[0], st.CARDS_HISTORY_TEXT, st.CARDS_HISTORY_URL),
          (st.PRODUCTS_TEXT[0], st.PRODUCT_LIST_TEXT, st.PRODUCT_LIST_URL),
          (st.PRODUCTS_TEXT[0], st.CATALOGS_TEXT, st.CATALOGS_URL),
          (st.PRODUCTS_TEXT[0], st.PRODUCT_RULES_TEXT, st.PRODUCT_RULES_URL),
          (st.PRODUCTS_TEXT[0], st.INVENTORY_TEXT, st.INVENTORY_URL),
          (st.FINANCE_TEXT[0], st.INVOICES_TEXT, st.INVOICES_URL),
          (st.FINANCE_TEXT[0], st.FUNDING_TEXT, st.FUNDING_URL),
          (st.FINANCE_TEXT[0], st.RECONCILIATION_TEXT, st.RECONCILIATION_URL),
          (st.FINANCE_TEXT[0], st.TRANSACTIONS_TEXT, st.TRANSACTIONS_URL),
          (st.MARKETPLACES_TEXT[0], st.ENEBA_TEXT, st.ENEBA_URL),
          (st.MARKETPLACES_TEXT[0], st.GAMIVO_TEXT, st.GAMIVO_URL),
          (st.REPORTS_TEXT[0], st.BRANDS_REPORT_TEXT, st.BRANDS_REPORT_URL)]

""" Clients """
CLIENT_NAME_1 = 'Olga UI autotests1'
EXCHANGE_RATE_1 = '0'
INTEGRATION_TYPE_1 = 'Client'
COMMERCIAL_STRUCTURE_1 = 'Rebate'
SETTLEMENT_METHOD_1 = 'Cash'
ACCOUNT_TYPE_1 = 'Prepaid'
INVOICE_FREQUENCY_1 = 'Weekly'

CLIENT_NAME_2 = 'Olga UI autotests2'
EXCHANGE_RATE_2 = '2'
INTEGRATION_TYPE_2 = 'Manual'
COMMERCIAL_STRUCTURE_2 = 'Discounts'
SETTLEMENT_METHOD_2 = 'Cheque'
ACCOUNT_TYPE_2 = 'Postpaid'
INVOICE_FREQUENCY_2 = 'Monthly'
EXCHANGE_RATE_2_EDIT = '1'
SETTLEMENT_METHOD_2_EDIT = 'BankTransfer'

CLIENT_NAME_3 = '1'
EXCHANGE_RATE_3 = '-1'
COMMERCIAL_STRUCTURE_3 = 'Rebate'
ACCOUNT_TYPE_3 = 'Postpaid'
SETTLEMENT_METHOD_3 = 'Paypal'

CLIENT_NAME_4 = 'Olga UI autotests4'
EXCHANGE_RATE_4 = '5'
INTEGRATION_TYPE_4 = 'Client'
COMMERCIAL_STRUCTURE_4 = 'Discounts'
ACCOUNT_TYPE_4 = 'Postpaid'
SETTLEMENT_METHOD_4 = 'Paypal'
INVOICE_FREQUENCY_4 = 'Daily'
ACCOUNT_CURRENCY_4 = 'EUR'

"""Client error messages"""
NAME_ERROR_MESSAGE = 'The name must not be shorter than 2 characters.'
INTEGRATION_ERROR_MESSAGE = 'Type is required.'


"""Brands"""
BRAND_NAME_1 = 'Olga UI test brand'
BRAND_CURRENCY_1 = 'AED'
BRAND_REGION_1 = 'United Arab Emirates'
BRAND_DESCRIPTION_1 = 'This is my test brand'
