""" Clients """
EXPECTED_CLIENT_1_STATUS = 'Active'
EXPECTED_CLIENT_1_CATALOG = 'No Catalogs for this Client'
EXPECTED_CLIENT_1_INTEGRATION = 'Api'
EXPECTED_CLIENT_1_COMMISSION = '0 %'
EXPECTED_CLIENT_2_STATUS = 'Active'
EXPECTED_CLIENT_2_CATALOG = 'No Catalogs for this Client'
EXPECTED_CLIENT_2_INTEGRATION = 'Manual'
EXPECTED_CLIENT_2_COMMISSION = '1 %'
