"""Expected results for cases"""


""" Clients """
EXPECTED_CLIENT_1_STATUS = 'Active'
EXPECTED_CLIENT_1_CATALOG = 'No Catalogs for this Client'
EXPECTED_CLIENT_1_INTEGRATION = 'Api'
EXPECTED_CLIENT_1_COMMISSION = '0 %'
EXPECTED_CLIENT_2_STATUS = 'Active'
EXPECTED_CLIENT_2_CATALOG = 'No Catalogs for this Client'
EXPECTED_CLIENT_2_INTEGRATION = 'Manual'
EXPECTED_CLIENT_2_COMMISSION = '1 %'

"""Brands"""
EXPECTED_BRAND_NAME_1 = 'UI Autotest do not touch object'

EXPECTED_BRAND_NAME_2 = 'Olga UI test brand'
EXPECTED_BRAND_CURRENCY_2 = 'AED'
EXPECTED_BRAND_SUPPLIER_2 = 'Non integrated suppliers'
EXPECTED_BRAND_REGION_2 = 'United Arab Emirates'


"""Suppliers"""
EXPECTED_ACCOUNTS_CY_SEND = ['CAD']
EXPECTED_ACCOUNTS_DIGGECARD = ['EUR', 'GBP']
EXPECTED_ACCOUNTS_EZPIN = ['USD', 'CAD', 'EUR', 'SAR', 'TRY', 'GBP', 'AED', 'EZD']
EXPECTED_ACCOUNTS_EPAY_MIDDLE_EAST = ['USD', 'EUR', 'AED']
EXPECTED_ACCOUNTS_JOKER_CODES_USD = ['USD']
EXPECTED_ACCOUNTS_JOKER_CODES_AED = ['SAR']
EXPECTED_ACCOUNTS_INCOMM = ['AUD', 'NZD', 'CAD', 'USD', 'HKD', 'GBP', 'EUR', 'EUR', 'MYR', 'SGD', 'AUD']
EXPECTED_ACCOUNTS_PREPAID_FORGE = ['EUR']


